/*
 * This file was generated by the Gradle "init" task.
 */

import subzero.Dependencies

plugins {
    id("com.squareup.subzero.java-conventions")
    id("com.google.protobuf") version "0.9.3"
}

dependencies {
    api(Dependencies.comGoogleProtobuf_ProtobufJava)
}

description = "proto"

protobuf {
    protoc {
        artifact = Dependencies.protocArtifact
    }
}

publishing {
    publications {
        register("mavenJava", MavenPublication::class) {
            groupId = group.toString()
            artifactId = "proto"
            version = version
            from(components["java"])
        }
    }
}

java {
    withSourcesJar()
}
