/*
 * This file was generated by the Gradle "init" task.
 */

import subzero.DependencyVersions

plugins {
    id("com.squareup.subzero.java-conventions")
    id("com.google.protobuf") version "0.9.3"
}

dependencies {
    api("com.google.protobuf:protobuf-java:${DependencyVersions.protobufJava}")
}

description = "proto"

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${DependencyVersions.protocArtifact}"
    }
}

publishing {
    publications {
        register("mavenJava", MavenPublication::class) {
            groupId = group.toString()
            artifactId = "proto"
            version = version
            from(components["java"])
        }
    }
}

java {
    withSourcesJar()
}
