/*
 * This file was generated by the Gradle "init" task.
 */

import com.github.jengelman.gradle.plugins.shadow.ShadowExtension
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import subzero.DependencyVersions

plugins {
    id("com.squareup.subzero.java-conventions")
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

dependencies {
    implementation("io.dropwizard:dropwizard-core:${DependencyVersions.dropwizard}") {
        // exclude vulnerable snakeyaml version 1.31 and replace with 2.0 below
        exclude("org.yaml", "snakeyaml")
    }
    implementation(project(":proto"))
    implementation("com.google.protobuf:protobuf-java-util:${DependencyVersions.protobuf}")
    implementation(project(":shared"))
    implementation("io.dropwizard:dropwizard-assets:${DependencyVersions.dropwizard}") {
        // exclude vulnerable snakeyaml version 1.31 and replace with 2.0 below
        exclude("org.yaml", "snakeyaml")
    }
    implementation("org.yaml:snakeyaml:${DependencyVersions.snakeyaml}")
}

description = "server"

tasks {
    // Disable non-shadow jar generation
    named<Jar>("jar") {
        enabled = false
    }

    // Configure shadow jar generation
    named<ShadowJar>("shadowJar") {
        enabled = true
        mergeServiceFiles()
        archiveClassifier.set("")
        manifest {
            attributes["Main-Class"] = "com.squareup.subzero.server.ServerApplication"
        }
        // signatures from foreign jars are bad news
        exclude("META-INF/*.SF")
        exclude("META-INF/*.DSA")
        exclude("META-INF/*.RSA")
    }

    // Make sure "gradle build" generates the shadow jar
    named("assemble") {
        dependsOn(":server:shadowJar")
    }
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            project.extensions.configure<ShadowExtension>() {
                component(this@create)
            }
        }
    }
}
