/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
    id("maven-publish")
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

group = "com.squareup.subzero"
version = "1.0.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8
java.targetCompatibility = JavaVersion.VERSION_1_8

publishing {
    repositories {
        mavenLocal()
    }
}

tasks {
    withType<JavaCompile>() {
        options.encoding = "UTF-8"
    }

    withType<Javadoc>() {
        options.encoding = "UTF-8"
    }

    // Needed for reproducible builds
    withType<AbstractArchiveTask>().configureEach {
        isPreserveFileTimestamps = false
        isReproducibleFileOrder = true
        // Fixing fileMode and dirMode is necessary for reproducible builds
        fileMode = "644".toInt(8)
        dirMode  = "775".toInt(8)
    }
}
