#!/bin/bash

# This script is run by anaconda after it has installed CentOS onto the ext4 disk image at /tmp/build/disk??????.img (and before our 1_post_install_chroot script has run).
# At runtime, that image is mounted at /mnt/sysimage/, so it’s the ideal time to copy misc files onto the new filesystem before it’s squashfs-ified.

# (Anaconda knows about this script because we reference it in a %post block in our custom rhel7-livemedia.ks kickstart.)

###############################################################################
# Copy nCipher CodeSafe to image
###############################################################################
mkdir /tmp/nfast_install
pushd /tmp/nfast_install

# CipherTools Developer
tar -xzf /media/SecWorld/linux/amd64/ctd.tar.gz

# Core Tools (recommended)
tar -xzf /media/SecWorld/linux/amd64/ctls.tar.gz

# nCore API Documentation
tar -xzf /media/SecWorld/linux/amd64/devref.tar.gz

# Hardware Support (mandatory)
tar -xzf /media/SecWorld/linux/amd64/hwsp.tar.gz

# Java Support (including nCipherKM JCA/JCE provider, KeySafe)
tar -xzf /media/SecWorld/linux/amd64/javasp.tar.gz

# Java dev libs for nCore API
tar -xzf /media/SecWorld/linux/amd64/jd.tar.gz

# nShield SNMP service and tools
tar -xzf /media/SecWorld/linux/amd64/ncsnmp.tar.gz

# Remote Administration Service (before 12.60 this package was known as dsserv)
tar -xzf /media/SecWorld/linux/amd64/raserv.tar.gz

# Redistributable GNU C shared libs
tar -xzf /media/SecWorld/linux/amd64/redist.tar.gz

# CodeSafe Developer; example programs, and SDK for CodeSafe
tar -xzf /media/CodeSafe/linux/amd64/csd.tar.gz

# Documentation for CodeSafe
tar -xzf /media/CodeSafe/linux/amd64/csdref.tar.gz

pushd opt
mv nfast /mnt/sysimage/opt/
popd
popd
rm -rf /tmp/nfast_install

###############################################################################
# Customize SYSLINUX bootloader background image
###############################################################################
cp /vagrant/syslinux-splash.png /mnt/sysimage/usr/share/anaconda/boot/syslinux-splash.png

###############################################################################
# Subzero DVD stuff
###############################################################################

mkdir -p /mnt/sysimage/data/app/subzero
cp -r /vagrant/data_app_subzero/* /mnt/sysimage/data/app/subzero
# pre-compiled protobuf compiler
cp /vagrant/protoc-3.14.0-linux-x86_64.zip /mnt/sysimage/data/app/subzero
# python wheels for protobuf
cp /vagrant/protobuf-3.14.0-cp36-cp36m-manylinux1_x86_64.whl /mnt/sysimage/data/app/subzero
cp /vagrant/six-1.15.0-py2.py3-none-any.whl /mnt/sysimage/data/app/subzero
