/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    id("com.squareup.subzero.java-conventions")
}

dependencies {
    api(project(":proto"))
    api("com.google.code.findbugs:jsr305:3.0.2")
    api("com.google.guava:guava:31.1-jre")
    api("com.google.zxing:core:3.5.0")
    api("com.madgag.spongycastle:core:1.58.0.0")
    api("org.apache.commons:commons-lang3:3.12.0")
    api("org.bitcoinj:bitcoinj-core:0.16.1") {
        exclude("com.google.protobuf", "protobuf-javalite")
    }
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.assertj:assertj-core:3.24.2")
}

description = "shared"

publishing {
    publications {
        register("mavenJava", MavenPublication::class) {
            groupId = group.toString()
            artifactId = "shared"
            version = version
            from(components["java"])
        }
    }
}
