/*
 * This file was generated by the Gradle "init" task.
 */

import subzero.Dependencies

plugins {
    id("com.squareup.subzero.java-conventions")
}

dependencies {
    api(project(":proto"))
    api(Dependencies.comGoogleCodeFindbugs_jsr305)
    api(Dependencies.comGoogleGuava_Guava)
    api(Dependencies.comGoogleZxing_Core)
    api(Dependencies.comMadgagSpongycastle_Core)
    api(Dependencies.orgBitcoinj_BitcoinjCore) {
        exclude("com.google.protobuf", "protobuf-javalite")
    }
    testImplementation(Dependencies.junit_Junit)
}

description = "shared"

publishing {
    publications {
        register("mavenJava", MavenPublication::class) {
            groupId = group.toString()
            artifactId = "shared"
            version = version
            from(components["java"])
        }
    }
}

java {
    withSourcesJar()
    withJavadocJar()
}
